FROM balenalib/%%BALENA-MACHINE-NAME%%-node:build

# Install build tools and remove layer cache afterwards
#RUN install_packages git python make gcc g++ libvips-dev

# Switch to working directory for our app
WORKDIR /usr/src/app

# Copy all the source code in.
COPY . .

RUN npm install sharp

RUN chmod u+x start.sh

# Launch our binary on container startup.
CMD ["bash", "start.sh"]