# Pinning to armv7hf so libvips compiles
FROM balenalib/armv7hf-node:build

# Switch to working directory for our app
WORKDIR /usr/src/app

# Copy all the source code in.
COPY . .

RUN npm install sharp

RUN chmod u+x start.sh

# Launch our binary on container startup.
CMD ["bash", "start.sh"]